### ISSUE TITLE
Digest crashes with md5

### ISSUE THREAD

**Issue by anordby** [varnish/libvmod-digest#2]
When I use digest.hash_md5 with any value Varnish crashes:

(gdb) bt
#0  0x0000000801caa5d7 in strlen () from /lib/libc.so.7
#1  0x0000000000440f0f in VRT_StringList (
    d=0x8083ce3e8 '0' <repeats 33 times>, "`??\t\bɵ(d\001Expect:", dl=63616, 
    p=0x800 <Error reading address 0x800: Bad address>, ap=0x7fffedb5a390)
    at cache_vrt.c:151
#2  0x00000000004410a9 in VRT_String (ws=0x8083cd080, 
    h=0x807502c56 "X-WURFL-Device:", p=0x8083ce3b0 '0' <repeats 32 times>, 
    ap=0x7fffedb5a390) at cache_vrt.c:186
#3  0x0000000000441431 in VRT_SetHdr (sp=0x8083cd008, where=HDR_REQ, 
    hdr=0x807502c55 "\017X-WURFL-Device:", 
    p=0x8083ce3b0 '0' <repeats 32 times>) at cache_vrt.c:230
#4  0x0000000807502338 in ?? ()
#5  0x00000008083cd398 in ?? ()
#6  0x000000000068272e in H_Expect ()
#7  0x0000000000000800 in ?? ()
#8  0x00007fffedb5a4d0 in ?? ()
#9  0x0000000802008400 in ?? ()
#10 0x000000000043faf7 in VCL_recv_method (sp=0x0) at vcl_returns.h:23
Previous frame inner to this frame (corrupt stack?)
(gdb) quit

My setup:

- the latest digest vmod from github (I pulled it today)

- varnish 3.0.3

- FreeBSD/amd64 9.1-RC1

- also using wurfl vmod by Scienta Mobile which I am testing

- digest.sha1 works fine. No crash.

**Comment by netw3rker** [comment]
I think this might still be an issue? am using a macports install of varnish-3.0.4, and a build of this off of the 3.0 branch. In addition, I had to build from source the mhash-0.9.9.9 library.

running "gmake check LD_PRELOAD=/usr/local/lib/libmhash.so" gives me the following test results:
```
root# gmake check LD_PRELOAD=/usr/local/lib/libmhash.so
Making check in src
gmake[1]: Entering directory '/opt/local/etc/varnish/source/libvmod-digest-3.0/src'
/opt/local/etc/varnish/source/varnish-3.0.4/bin/varnishtest/varnishtest -Dvarnishd=/opt/local/etc/varnish/source/varnish-3.0.4/bin/varnishd/varnishd -Dvmod_topbuild=/opt/local/etc/varnish/source/libvmod-digest-3.0 tests/test01.vtc
**** top   0.0 macro def varnishd=/opt/local/etc/varnish/source/varnish-3.0.4/bin/varnishd/varnishd
**** top   0.0 macro def vmod_topbuild=/opt/local/etc/varnish/source/libvmod-digest-3.0
**** top   0.0 macro def pwd=/opt/local/etc/varnish/source/libvmod-digest-3.0/src
**** top   0.0 macro def topbuild=/opt/local/etc/varnish/source/libvmod-digest-3.0/src/../..
**** top   0.0 macro def bad_ip=192.0.2.255
**** top   0.0 macro def tmpdir=/tmp/vtc.56939.666452bd
*    top   0.0 TEST tests/test01.vtc starting
***  top   0.0 varnishtest
*    top   0.0 TEST Test digest vmod
***  top   0.0 server
**   s1    0.0 Starting server
**** s1    0.0 macro def s1_addr=127.0.0.1
**** s1    0.0 macro def s1_port=53197
**** s1    0.0 macro def s1_sock=127.0.0.1 53197
*    s1    0.0 Listen on 127.0.0.1 53197
**   s1    0.0 Started on 127.0.0.1 53197
***  top   0.0 varnish
**   v1    0.0 Launch
***  v1    0.0 CMD: cd ${pwd} && ${varnishd} -d -d -n /tmp/vtc.56939.666452bd/v1 -l 10m,1m,- -p auto_restart=off -p syslog_cli_traffic=off -a '127.0.0.1:0' -S /tmp/vtc.56939.666452bd/v1/_S -M '127.0.0.1 53198' -P /tmp/vtc.56939.666452bd/v1/varnishd.pid -sfile,/tmp/vtc.56939.666452bd/v1,10M 
***  v1    0.0 CMD: cd /opt/local/etc/varnish/source/libvmod-digest-3.0/src && /opt/local/etc/varnish/source/varnish-3.0.4/bin/varnishd/varnishd -d -d -n /tmp/vtc.56939.666452bd/v1 -l 10m,1m,- -p auto_restart=off -p syslog_cli_traffic=off -a '127.0.0.1:0' -S /tmp/vtc.56939.666452bd/v1/_S -M '127.0.0.1 53198' -P /tmp/vtc.56939.666452bd/v1/varnishd.pid -sfile,/tmp/vtc.56939.666452bd/v1,10M 
***  v1    0.0 PID: 56957
***  v1    0.1 debug| Platform: Darwin,14.1.0,x86_64,-sfile,-smalloc,-hcritbit\n
***  v1    0.1 debug| 200 264     \n
***  v1    0.1 debug| -----------------------------\n
***  v1    0.1 debug| Varnish Cache CLI 1.0\n
***  v1    0.1 debug| -----------------------------\n
***  v1    0.1 debug| Darwin,14.1.0,x86_64,-sfile,-smalloc,-hcritbit\n
***  v1    0.1 debug| varnish-3.0.4 revision 9f83e8f\n
***  v1    0.1 debug| \n
***  v1    0.1 debug| Type 'help' for command list.\n
***  v1    0.1 debug| Type 'quit' to close CLI session.\n
***  v1    0.1 debug| Type 'start' to launch worker process.\n
***  v1    0.1 debug| \n
**** v1    0.2 CLIPOLL 1 0x1 0x0
***  v1    0.2 CLI connection fd = 8
***  v1    0.2 CLI RX  107
**** v1    0.2 CLI RX| txyeehlozzmkuiszmsjiuvcxjjosplai\n
**** v1    0.2 CLI RX| \n
**** v1    0.2 CLI RX| Authentication required.\n
**** v1    0.2 CLI TX| auth 55b16955d46c5ee57a071e9a89b3c025c2c4f65598e671f40646314ce5ad82db\n
***  v1    0.2 CLI RX  200
**** v1    0.2 CLI RX| -----------------------------\n
**** v1    0.2 CLI RX| Varnish Cache CLI 1.0\n
**** v1    0.2 CLI RX| -----------------------------\n
**** v1    0.2 CLI RX| Darwin,14.1.0,x86_64,-sfile,-smalloc,-hcritbit\n
**** v1    0.2 CLI RX| varnish-3.0.4 revision 9f83e8f\n
**** v1    0.2 CLI RX| \n
**** v1    0.2 CLI RX| Type 'help' for command list.\n
**** v1    0.2 CLI RX| Type 'quit' to close CLI session.\n
**** v1    0.2 CLI RX| Type 'start' to launch worker process.\n
**** v1    0.2 CLI TX| vcl.inline vcl1 << %XJEIFLH|)Xspa8P\n
**** v1    0.2 CLI TX| backend s1 { .host = "127.0.0.1"; .port = "53197"; }\n
**** v1    0.2 CLI TX| \n
**** v1    0.2 CLI TX| \n
**** v1    0.2 CLI TX| \timport digest from "/opt/local/etc/varnish/source/libvmod-digest-3.0/src/.libs/libvmod_digest.so";\n
**** v1    0.2 CLI TX| \n
**** v1    0.2 CLI TX| \tsub vcl_deliver {\n
**** v1    0.2 CLI TX| \t\tset resp.http.sha256 = digest.hmac_sha256("key", "The quick brown fox jumps over the lazy dog");\n
**** v1    0.2 CLI TX| \t\tset resp.http.sha1 = digest.hmac_sha1("key", "The quick brown fox jumps over the lazy dog");\n
**** v1    0.2 CLI TX| \t\tset resp.http.md5 = digest.hmac_md5("key", "The quick brown fox jumps over the lazy dog");\n
**** v1    0.2 CLI TX| \t\tset resp.http...
***  v1    0.3 CLI RX  200
**** v1    0.3 CLI RX| VCL compiled.
**** v1    0.3 CLI TX| vcl.use vcl1
***  v1    0.3 CLI RX  200
**   v1    0.3 Start
**** v1    0.3 CLI TX| start
***  v1    0.3 debug| child (56979) Started\n
**** v1    0.3 vsl|     0 WorkThread   - 0x10fa14b00 start
**** v1    0.3 vsl|     0 CLI          - Rd vcl.load "vcl1" ./vcl.It4ikVeR.so
***  v1    0.3 CLI RX  200
***  v1    0.3 wait-running
**** v1    0.3 CLI TX| status
***  v1    0.3 debug| Child (56979) said Child starts\n
***  v1    0.3 debug| Child (56979) said SMF.s0 mmap'ed 10485760 bytes of 10485760\n
***  v1    0.3 CLI RX  200
**** v1    0.3 CLI RX| Child in state running
**** v1    0.3 CLI TX| debug.xid 1000
***  v1    0.3 CLI RX  200
**** v1    0.3 CLI RX| XID is 1000
**** v1    0.3 CLI TX| debug.listen_address
***  v1    0.3 CLI RX  200
**** v1    0.3 CLI RX| 127.0.0.1 53200\n
**   v1    0.3 Listen on 127.0.0.1 53200
**** v1    0.3 macro def v1_addr=127.0.0.1
**** v1    0.3 macro def v1_port=53200
**** v1    0.3 macro def v1_sock=127.0.0.1 53200
***  top   0.3 client
***  top   0.3 client
**   c1    0.3 Starting client
**   c1    0.3 Waiting for client
***  c1    0.3 Connect to 127.0.0.1 53200
***  c1    0.3 connected fd 9 from 127.0.0.1 53201 to 127.0.0.1 53200
**** v1    0.3 vsl|     0 CLI          - Wr 200 36 Loaded "./vcl.It4ikVeR.so" as "vcl1"
**** v1    0.3 vsl|     0 CLI          - Rd vcl.use "vcl1"
**** v1    0.3 vsl|     0 CLI          - Wr 200 0 
**** v1    0.3 vsl|     0 CLI          - Rd start
***  c1    0.3 txreq
**** v1    0.3 vsl|     0 Debug        - Acceptor is kqueue
**** v1    0.3 vsl|     0 CLI          - Wr 200 0 
**** v1    0.3 vsl|     0 CLI          - Rd debug.xid 1000 
**** v1    0.3 vsl|     0 CLI          - Wr 200 11 XID is 1000
**** v1    0.3 vsl|     0 CLI          - Rd debug.listen_address 
**** v1    0.3 vsl|     0 CLI          - Wr 200 16 127.0.0.1 53200

**** c1    0.3 txreq| GET / HTTP/1.1\r\n
**** c1    0.3 txreq| \r\n
***  c1    0.3 rxresp
**** v1    0.3 vsl|     0 WorkThread   - 0x1107e2b00 start
**** v1    0.3 vsl|     0 WorkThread   - 0x110865b00 start
**** v1    0.3 vsl|     0 WorkThread   - 0x1108e8b00 start
**** v1    0.3 vsl|     0 WorkThread   - 0x11096bb00 start
***  s1    0.3 accepted fd 10
***  s1    0.3 rxreq
**** s1    0.3 rxhdr| GET / HTTP/1.1\r\n
**** s1    0.3 rxhdr| X-Forwarded-For: 127.0.0.1\r\n
**** s1    0.3 rxhdr| X-Varnish: 1001\r\n
**** s1    0.3 rxhdr| Accept-Encoding: gzip\r\n
**** s1    0.3 rxhdr| Host: 127.0.0.1\r\n
**** s1    0.3 rxhdr| \r\n
**** s1    0.3 http[ 0] | GET
**** s1    0.3 http[ 1] | /
**** s1    0.3 http[ 2] | HTTP/1.1
**** s1    0.3 http[ 3] | X-Forwarded-For: 127.0.0.1
**** s1    0.3 http[ 4] | X-Varnish: 1001
**** s1    0.3 http[ 5] | Accept-Encoding: gzip
**** s1    0.3 http[ 6] | Host: 127.0.0.1
**** s1    0.3 bodylen = 0
***  s1    0.3 txresp
**** s1    0.3 txresp| HTTP/1.1 200 Ok\r\n
**** s1    0.3 txresp| Content-Length: 0\r\n
**** s1    0.3 txresp| \r\n
***  s1    0.3 shutting fd 10
**   s1    0.3 Ending
**** v1    0.3 vsl|     0 WorkThread   - 0x1109eeb00 start
**** v1    0.3 vsl|     7 SessionOpen  c 127.0.0.1 53201 127.0.0.1:0
**** v1    0.3 vsl|     7 ReqStart     c 127.0.0.1 53201 1001
**** v1    0.3 vsl|     7 RxRequest    c GET
**** v1    0.3 vsl|     7 RxURL        c /
**** v1    0.3 vsl|     7 RxProtocol   c HTTP/1.1
**** v1    0.3 vsl|     7 VCL_call     c recv
**** v1    0.3 vsl|     7 VCL_return   c lookup
**** v1    0.3 vsl|     7 VCL_call     c hash
**** v1    0.3 vsl|     7 Hash         c /
**** v1    0.3 vsl|     7 Hash         c 127.0.0.1
**** v1    0.3 vsl|     7 VCL_return   c hash
**** v1    0.3 vsl|     7 VCL_call     c miss
**** v1    0.3 vsl|     7 VCL_return   c fetch
**** v1    0.3 vsl|    10 BackendOpen  b s1 127.0.0.1 53202 127.0.0.1 53197
**** v1    0.3 vsl|     7 Backend      c 10 s1 s1
**** v1    0.3 vsl|    10 TxRequest    b GET
**** v1    0.3 vsl|    10 TxURL        b /
**** v1    0.3 vsl|    10 TxProtocol   b HTTP/1.1
**** v1    0.3 vsl|    10 TxHeader     b X-Forwarded-For: 127.0.0.1
**** v1    0.3 vsl|    10 TxHeader     b X-Varnish: 1001
**** v1    0.3 vsl|    10 TxHeader     b Accept-Encoding: gzip
**** v1    0.3 vsl|    10 TxHeader     b Host: 127.0.0.1
**** v1    0.3 vsl|    10 RxProtocol   b HTTP/1.1
**** v1    0.3 vsl|    10 RxStatus     b 200
**** v1    0.3 vsl|    10 RxResponse   b Ok
**** v1    0.3 vsl|    10 RxHeader     b Content-Length: 0
**** v1    0.3 vsl|     7 TTL          c 1001 RFC 120 -1 -1 1429499934 0 0 0 0
**** v1    0.3 vsl|     7 VCL_call     c fetch
**** v1    0.3 vsl|     7 VCL_return   c deliver
**** v1    0.3 vsl|     7 ObjProtocol  c HTTP/1.1
**** v1    0.3 vsl|     7 ObjResponse  c Ok
**** v1    0.3 vsl|    10 Fetch_Body   b 4(length) cls 0 mklen 1
**** v1    0.3 vsl|    10 Length       b 0
**** v1    0.3 vsl|    10 BackendReuse b s1
---- c1    0.6 HTTP rx EOF (fd:9 read: Undefined error: 0)
***  v1    0.6 debug| Child (56979) died signal=11\n
*    top   0.6 RESETTING after tests/test01.vtc
**   s1    0.6 Waiting for server
**** s1    0.6 macro undef s1_addr
**** s1    0.6 macro undef s1_port
**** s1    0.6 macro undef s1_sock
***  v1    0.6 debug| Child cleanup complete\n
**   v1    1.6 Wait
**   v1    1.6 R 56957 Status: 0000
*    top   1.6 TEST tests/test01.vtc FAILED

#     top  TEST tests/test01.vtc FAILED (1.569) exit=1
Makefile:659: recipe for target 'tests/test01.vtc' failed
gmake[1]: *** [tests/test01.vtc] Error 2
gmake[1]: Leaving directory '/opt/local/etc/varnish/source/libvmod-digest-3.0/src'
Makefile:495: recipe for target 'check-recursive' failed
gmake: *** [check-recursive] Error 1
```

any thoughts on how to get varnish to stop dying with md5 is called?

**Comment by aondio** [comment]
I'll reopen this issue.
I've checked the behavior on linux and debian and I haven't been able to reproduce such an error.
This should be just freebsd related.

**Comment by daghf** [comment]
Please try a more recent version, if you can still reproduce it feel free to reopen.
